# Generated by Django 5.2.3 on 2025-06-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for the budget item.', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, help_text='The monetary value of the budget item (e.g., 50.00).', max_digits=10)),
                ('repeating', models.BooleanField(default=False, help_text='Indicates if this budget item is a recurring expense/income.')),
                ('start_date', models.DateField(blank=True, help_text='Optional: The start date for the budget item, especially for repeating items.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional: The end date for the budget item, especially for repeating items.', null=True)),
                ('owner', models.ForeignKey(help_text='The user who owns this budget item.', on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Items',
                'ordering': ['name', 'start_date'],
            },
        ),
    ]
