# Generated by Django 5.2.3 on 2025-06-27 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025, help_text='The year for this budget month (e.g., 2025)')),
                ('month_number', models.IntegerField(default=6, help_text='The month number (1 for January, 12 for December)')),
                ('owner', models.ForeignKey(blank=True, help_text='Optional: The user who owns this budget month, or leave blank for global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_months', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Month',
                'verbose_name_plural': 'Budget Months',
                'ordering': ['year', 'month_number'],
                'unique_together': {('year', 'month_number', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='month',
            field=models.ForeignKey(blank=True, help_text='Optional: The month this budget item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='planner.month'),
        ),
    ]
