# Generated by Django 5.2.3 on 2025-06-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_month_budgetitem_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('year', 'month_number')},
        ),
        migrations.RemoveField(
            model_name='month',
            name='owner',
        ),
    ]
