# Generated by Django 5.2.3 on 2025-06-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_month_unique_together_remove_month_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', help_text='Category of the budget item (Income or Expense).', max_length=10),
        ),
    ]
